name: "Fraser Lab"
description: "This is the official web page for the James Fraser Lab at UCSF."

url: "https://fraserlab.com"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        affiliates:
                output: false
        members:
                output: false
        publications:
                output: false
        reviews:
                output: false
        alumni:
                output: false
        sep:
                output: false
        visitors:
                output: false
        undergrads:
                output: false
        pets:
                output: false
        tags:
                output: true
        authors:
                output: true